import { useEffect, useState } from 'react';
import { hospitalService } from '../../api/hospitalService';
import { Icon } from '../../components/common/AppUi';

const items = (payload) => Array.isArray(payload) ? payload : payload?.content || [];

export default function HospitalsPage({ onToast }) {
  const [mode, setMode] = useState('search'); const [name, setName] = useState(''); const [radius, setRadius] = useState(10); const [hospitals, setHospitals] = useState([]); const [loading, setLoading] = useState(false);
  const search = async (event) => { event?.preventDefault(); setLoading(true); try { let payload; if (mode === 'nearby') { if (!navigator.geolocation) throw new Error('Location is not available in this browser'); const position = await new Promise((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { timeout: 8000 })); payload = await hospitalService.nearby({ lat: position.coords.latitude, lng: position.coords.longitude, radius: Number(radius) }); } else payload = await hospitalService.search({ ...(name ? { name } : {}) }); setHospitals(items(payload)); } catch (err) { onToast(err.message || 'Unable to load hospitals'); } finally { setLoading(false); } };
  // Load the default hospital list when the locator opens.
  useEffect(() => { search(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="view-stack"><div className="page-heading"><div><p className="eyebrow">CARE LOCATOR</p><h1>Find a hospital</h1><p className="muted">Search hospitals by name or discover care close to your current location.</p></div></div><section className="panel hospital-search-panel"><div className="segmented"><button className={mode === 'search' ? 'selected' : ''} onClick={() => setMode('search')}>Search by name</button><button className={mode === 'nearby' ? 'selected' : ''} onClick={() => setMode('nearby')}>Nearby</button></div><form className="hospital-search-form" onSubmit={search}>{mode === 'search' ? <label className="field"><span>Hospital name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Korle Bu" /></label> : <label className="field"><span>Search radius (km)</span><input type="number" min="1" max="100" value={radius} onChange={(e) => setRadius(e.target.value)} /></label>}<button className="primary-button" type="submit" disabled={loading}><Icon name={mode === 'nearby' ? 'pin' : 'refresh'} size={16} /> {loading ? 'Searching...' : 'Search hospitals'}</button></form></section><section className="hospital-list">{hospitals.length ? hospitals.map((hospital) => <article className="panel hospital-card" key={hospital.id}><div className="hospital-card-icon"><Icon name="pin" /></div><div className="hospital-card-copy"><h2>{hospital.name || 'Hospital'}</h2><p>{hospital.address || 'Address not provided'}</p><div className="hospital-meta">{hospital.phone && <span>{hospital.phone}</span>}{hospital.email && <span>{hospital.email}</span>}{hospital.distanceKm != null && <span>{Number(hospital.distanceKm).toFixed(1)} km away</span>}</div></div></article>) : <section className="panel empty-state"><Icon name="pin" size={28} /><h2>No hospitals found</h2><p className="muted">Try a different name or search radius.</p></section>}</section></div>;
}
