import { useEffect, useState } from 'react';
import { questionService } from '../../api/questionService';
import { Icon } from '../../components/common/AppUi';

export default function QuestionsPanel({ appointmentId, doctorMode = false, onToast }) {
  const [questions, setQuestions] = useState([]); const [question, setQuestion] = useState(''); const [answers, setAnswers] = useState({}); const [loading, setLoading] = useState(true);
  const load = async () => { try { setQuestions(await questionService.list(appointmentId) || []); } catch (err) { onToast(err.message); } finally { setLoading(false); } };
  useEffect(() => { if (appointmentId) load(); }, [appointmentId]); // eslint-disable-line react-hooks/exhaustive-deps
  const ask = async () => { if (!question.trim()) return; try { const created = await questionService.ask(appointmentId, question.trim()); setQuestions((items) => [...items, created]); setQuestion(''); onToast('Question sent'); } catch (err) { onToast(err.message); } };
  const answer = async (item) => { if (!answers[item.id]?.trim()) return; try { const updated = await questionService.answer(appointmentId, item.id, answers[item.id].trim()); setQuestions((items) => items.map((entry) => entry.id === item.id ? updated : entry)); setAnswers((current) => ({ ...current, [item.id]: '' })); onToast('Answer sent'); } catch (err) { onToast(err.message); } };
  return <section className="questions-panel"><div className="panel-heading"><div><p className="eyebrow">CARE TEAM</p><h2>Questions & answers</h2></div><Icon name="help" size={17} /></div>{loading ? <p className="muted">Loading conversation...</p> : questions.length ? questions.map((item) => <div className="question-item" key={item.id}><div><b>{item.question}</b><small>{item.patientName || 'Patient'} · {item.createdAt ? new Date(item.createdAt).toLocaleString() : 'Recently'}</small></div>{item.answer ? <div className="answer-copy"><span>Answer</span><p>{item.answer}</p></div> : doctorMode ? <div className="answer-form"><input value={answers[item.id] || ''} onChange={(e) => setAnswers((current) => ({ ...current, [item.id]: e.target.value }))} placeholder="Write an answer" /><button className="tiny-button approve" onClick={() => answer(item)}>Answer</button></div> : <small className="muted">Awaiting doctor response</small>}</div>) : <p className="muted">No questions yet.</p>}{!doctorMode && <div className="ask-form"><input value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask your care team a question" /><button className="primary-button" onClick={ask}><Icon name="plus" size={15} /> Ask</button></div>}</section>;
}
