import { useEffect, useState } from 'react';
import { hospitalService } from '../../api/hospitalService';
import { Icon } from '../../components/common/AppUi';

const empty = { name: '', address: '', latitude: '', longitude: '', phone: '', email: '' };
const items = (payload) => Array.isArray(payload) ? payload : payload?.content || [];
export default function AdminHospitalsPage({ onToast }) {
  const [hospitals, setHospitals] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(false);
  const load = async () => { try { setHospitals(items(await hospitalService.search())); } catch (err) { onToast(err.message); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const save = async (event) => { event.preventDefault(); setLoading(true); const payload = { ...form, latitude: form.latitude ? Number(form.latitude) : null, longitude: form.longitude ? Number(form.longitude) : null }; try { const result = editing ? await hospitalService.update(editing, payload) : await hospitalService.create(payload); setHospitals((list) => editing ? list.map((item) => item.id === editing ? result : item) : [result, ...list]); setForm(empty); setEditing(null); onToast(editing ? 'Hospital updated' : 'Hospital created'); } catch (err) { onToast(err.message); } finally { setLoading(false); } };
  const remove = async (id) => { if (!window.confirm('Delete this hospital?')) return; try { await hospitalService.remove(id); setHospitals((list) => list.filter((item) => item.id !== id)); onToast('Hospital deleted'); } catch (err) { onToast(err.message); } };
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  return <div className="view-stack"><div className="page-heading"><div><p className="eyebrow">SYSTEM CONFIGURATION</p><h1>Hospitals</h1><p className="muted">Manage care locations available to patients.</p></div></div><form className="panel hospital-admin-form" onSubmit={save}><div className="panel-heading"><div><p className="eyebrow">{editing ? 'EDIT LOCATION' : 'NEW LOCATION'}</p><h2>{editing ? 'Update hospital' : 'Add hospital'}</h2></div>{editing && <button type="button" className="text-button" onClick={() => { setEditing(null); setForm(empty); }}>Cancel edit</button>}</div><div className="form-grid">{[['name','Name'],['address','Address'],['phone','Phone'],['email','Email'],['latitude','Latitude'],['longitude','Longitude']].map(([key,label]) => <label className="field" key={key}><span>{label}</span><input value={form[key]} onChange={update(key)} required={key === 'name' || key === 'address'} /></label>)}</div><button className="primary-button" disabled={loading}><Icon name="check" size={15} /> {loading ? 'Saving...' : editing ? 'Save changes' : 'Create hospital'}</button></form><section className="panel table-panel"><div className="table-head hospital-table-head"><span>HOSPITAL</span><span>CONTACT</span><span>LOCATION</span><span>ACTION</span></div>{hospitals.length ? hospitals.map((item) => <div className="table-row hospital-table-row" key={item.id}><div><b>{item.name}</b><small>{item.address || 'Address not provided'}</small></div><div><b>{item.phone || '-'}</b><small>{item.email || '-'}</small></div><div><small>{item.latitude ?? '-'}, {item.longitude ?? '-'}</small></div><div className="admin-actions"><button className="tiny-button approve" onClick={() => { setEditing(item.id); setForm({ ...empty, ...item, latitude: item.latitude ?? '', longitude: item.longitude ?? '' }); }}>Edit</button><button className="tiny-button reject" onClick={() => remove(item.id)}>Delete</button></div></div>) : <div className="empty-table">No hospitals found.</div>}</section></div>;
}
