import { useEffect, useState } from 'react';
import { adminService } from '../../api/adminService';
import { hospitalService } from '../../api/hospitalService';
import { Icon } from '../../components/common/AppUi';

const days = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'];
const blank = { email: '', password: '', firstName: '', lastName: '', specialty: '', hospitalId: '', consultationDurationMinutes: 30, availableDays: [] };
const list = (payload) => Array.isArray(payload) ? payload : payload?.content || [];

export default function AdminDoctorsPage({ onToast }) {
  const [form, setForm] = useState(blank); const [hospitals, setHospitals] = useState([]); const [startTime, setStartTime] = useState('09:00'); const [endTime, setEndTime] = useState('17:00'); const [busy, setBusy] = useState(false);
  useEffect(() => { hospitalService.search().then((payload) => setHospitals(list(payload))).catch((err) => onToast(err.message)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const toggleDay = (day) => setForm((current) => ({ ...current, availableDays: current.availableDays.includes(day) ? current.availableDays.filter((item) => item !== day) : [...current.availableDays, day] }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { const availableDays = form.availableDays.reduce((result, day) => ({ ...result, [day]: [`${startTime}-${endTime}`] }), {}); const result = await adminService.createDoctor({ ...form, hospitalId: Number(form.hospitalId), consultationDurationMinutes: Number(form.consultationDurationMinutes), availableDays }); onToast(`Doctor account created for ${result.email}`); setForm({ ...blank, hospitalId: form.hospitalId }); } catch (err) { onToast(err.message); } finally { setBusy(false); } };
  return <div className="view-stack"><div className="page-heading"><div><p className="eyebrow">STAFF MANAGEMENT</p><h1>Register a doctor</h1><p className="muted">Create an enabled doctor account and assign it to a hospital.</p></div></div><form className="panel doctor-registration-form" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">ACCOUNT DETAILS</p><h2>Doctor registration</h2></div><Icon name="user" /></div><div className="form-grid"><label className="field"><span>First name</span><input value={form.firstName} onChange={update('firstName')} required /></label><label className="field"><span>Last name</span><input value={form.lastName} onChange={update('lastName')} required /></label><label className="field"><span>Email address</span><input type="email" value={form.email} onChange={update('email')} required /></label><label className="field"><span>Temporary password</span><input type="password" minLength="6" value={form.password} onChange={update('password')} required /></label><label className="field"><span>Specialty</span><input value={form.specialty} onChange={update('specialty')} placeholder="Cardiology" required /></label><label className="select-field"><span>Hospital</span><select value={form.hospitalId} onChange={update('hospitalId')} required><option value="">Select hospital</option>{hospitals.map((hospital) => <option key={hospital.id} value={hospital.id}>{hospital.name}</option>)}</select></label><label className="field"><span>Consultation duration (minutes)</span><input type="number" min="5" max="240" step="5" value={form.consultationDurationMinutes} onChange={update('consultationDurationMinutes')} required /></label></div><div className="registration-section"><p className="eyebrow">DEFAULT AVAILABILITY</p><div className="day-picker">{days.map((day) => <label className={form.availableDays.includes(day) ? 'day-option selected' : 'day-option'} key={day}><input type="checkbox" checked={form.availableDays.includes(day)} onChange={() => toggleDay(day)} /><span>{day.slice(0, 3)}</span></label>)}</div><div className="form-grid availability-fields"><label className="field"><span>Start time</span><input type="time" value={startTime} onChange={(e) => setStartTime(e.target.value)} /></label><label className="field"><span>End time</span><input type="time" value={endTime} onChange={(e) => setEndTime(e.target.value)} /></label></div></div><button className="primary-button" disabled={busy || !hospitals.length}><Icon name="check" size={15} /> {busy ? 'Creating account...' : 'Create doctor account'}</button>{!hospitals.length && <p className="form-hint">Create a hospital first before registering a doctor.</p>}</form></div>;
}
